import React from 'react'

const Avatar = function (props) {

    return (
        <img src={`http://react-avatars.ml/adventurer.svg`} alt="Avatar generated by React-Avatars" style={{
            height: props.size + 'px',
            borderRadius: '50%',
            backgroundColor: props.bg,
            paddingTop: '1px'
        }} />
    )
}

Avatar.defaultProps = {
    size: 60,
    seed: null,
    bg: '#E5E5E5'
}

export default Avatar
