import React from 'react'

const Avatar = function (props) {

    function getSeed() {
        if (props.seed != null) {
            return props.seed
        } 
        return Math.floor(Math.random()*999999999)
    }

    return (
        <div className="adventure-avatar">
            <img src={`https://avatars.dicebear.com/api/micah/${getSeed()}.svg`} alt="Avatar generated by Adventure Avatars" style={{
                height: props.size + 'px',
                borderRadius: '50%',
                backgroundColor: props.bg,
                paddingTop: '1px'
            }} />
        </div>
    )
}

Avatar.defaultProps = {
    size: 60,
    seed: null,
    bg: '#E5E5E5'
}

export default Avatar
